### ISSUE TITLE
General source path

### ISSUE THREAD

**Issue by hawkeyexp** [notro/rpi-source#43]
Hi,

first: a great script !

But one point: why not using /usr/src for example to place the kernel source instead of placing it into /root home dir ?

**Comment by notro** [comment]
The idea is to run the script as the pi user, _not_ as root or with sudo. The source is put in the home folder. /user/src is read-only for regular users. You can override destination with ```-d <folder>```. The script uses sudo internally in order to create a couple of symlinks. rpi-source was created to make it easy for novices to build out-of-tree modules. Nowadays there's a kernel header package, but still people finds use for it. Maybe because they use old howtos that hasn't been updated? I don't know.

**Comment by kapitainsky** [comment]
kernel header package is often behind the latest kernel releases so this script is mega useful.
